window.appData = window.appData || {};
window.appData.armor = [
    {
        "File name":  "ia_class4_001.png",
        "Icon":  "",
        "Name":  "Combat Suit",
        "Type":  "Armor",
        "Subtype":  "Light",
        "Defense Rating":  "1d4",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "TRUE"
    },
    {
        "File name":  "ia_class4_002.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor",
        "Subtype":  "Light",
        "Defense Rating":  "1d4",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "TRUE"
    },
    {
        "File name":  "ia_class4_003.png",
        "Icon":  "",
        "Name":  "Echani Light Armor",
        "Type":  "Armor",
        "Subtype":  "Light",
        "Defense Rating":  "1d4",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "TRUE"
    },
    {
        "File name":  "ia_class4_004.png",
        "Icon":  "",
        "Name":  "Light Combat Suit",
        "Type":  "Armor",
        "Subtype":  "Light",
        "Defense Rating":  "1d4",
        "Description":  "The lightest form of armor available, the light combat suit is very inexpensive and still notably superior to normal civilian garb.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "TRUE"
    },
    {
        "File name":  "ia_class4_005.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor",
        "Subtype":  "Light",
        "Defense Rating":  "1d4",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "TRUE"
    },
    {
        "File name":  "ia_class4_006.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor",
        "Subtype":  "Light",
        "Defense Rating":  "1d4",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "TRUE"
    },
    {
        "File name":  "ia_class4_007.png",
        "Icon":  "",
        "Name":  "Electromesh Suit",
        "Type":  "Armor",
        "Subtype":  "Light",
        "Defense Rating":  "1d4",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "TRUE"
    },
    {
        "File name":  "ia_class4_008.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor",
        "Subtype":  "Light",
        "Defense Rating":  "1d4",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "TRUE"
    },
    {
        "File name":  "ia_class4_009.png",
        "Icon":  "",
        "Name":  "Miner Uniform",
        "Type":  "Armor",
        "Subtype":  "Light",
        "Defense Rating":  "1d4",
        "Description":  "This is a standard uniform worn by miners at the Peragus facility. It provides minimal protection, but can be upgraded with some underlays.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "TRUE"
    },
    {
        "File name":  "ia_class5_001.png",
        "Icon":  "",
        "Name":  "Heavy Combat Suit",
        "Type":  "Armor",
        "Subtype":  "Light",
        "Defense Rating":  "1d4+1",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "TRUE"
    },
    {
        "File name":  "ia_class5_002.png",
        "Icon":  "",
        "Name":  "Bonadan Alloy Heavy Suit",
        "Type":  "Armor",
        "Subtype":  "Light",
        "Defense Rating":  "1d4+1",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "TRUE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "TRUE"
    },
    {
        "File name":  "ia_class5_003.png",
        "Icon":  "",
        "Name":  "Zabrak Battle Armor",
        "Type":  "Armor",
        "Subtype":  "Light",
        "Defense Rating":  "1d4+1",
        "Description":  "On the far northern continent of the planet Iridonia, the Zabrak produce expensive armor that nonetheless has become very popular on the galactic markets, due to excellent low-temperature defensive properties.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "TRUE"
    },
    {
        "File name":  "ia_class5_004.png",
        "Icon":  "",
        "Name":  "Zabrak Field Armor",
        "Type":  "Armor",
        "Subtype":  "Light",
        "Defense Rating":  "1d4+1",
        "Description":  "This is a higher-quality version of the basic armor produced by the Zabrak. These were often reserved for field commanders, and meant to be easily identified on the battlefield.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "TRUE"
    },
    {
        "File name":  "ia_class5_005.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor",
        "Subtype":  "Light",
        "Defense Rating":  "1d4+1",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "TRUE"
    },
    {
        "File name":  "ia_class5_006.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor",
        "Subtype":  "Light",
        "Defense Rating":  "1d4+1",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "TRUE"
    },
    {
        "File name":  "ia_class5_007.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor",
        "Subtype":  "Light",
        "Defense Rating":  "1d4+1",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "TRUE"
    },
    {
        "File name":  "ia_class5_008.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor",
        "Subtype":  "Light",
        "Defense Rating":  "1d4+1",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "TRUE"
    },
    {
        "File name":  "ia_class5_009.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor",
        "Subtype":  "Light",
        "Defense Rating":  "1d4+1",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "TRUE"
    },
    {
        "File name":  "ia_class5_010.png",
        "Icon":  "",
        "Name":  "Khoonda Militia Armor",
        "Type":  "Armor",
        "Subtype":  "Light",
        "Defense Rating":  "1d4+1",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "TRUE"
    },
    {
        "File name":  "ia_class6_001.png",
        "Icon":  "",
        "Name":  "Military Suit",
        "Type":  "Armor",
        "Subtype":  "Medium",
        "Defense Rating":  "1d6",
        "Description":  "This standard issue suit provides good protection, but can be heavier and more restrictive than some of its counterparts. Even so, many mercenaries swear the tradeoffs are worth it.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "TRUE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "TRUE"
    },
    {
        "File name":  "ia_class6_002.png",
        "Icon":  "",
        "Name":  "Echani Battle Armor",
        "Type":  "Armor",
        "Subtype":  "Medium",
        "Defense Rating":  "1d6",
        "Description":  "This armor provides solid defense at the cost of some flexibility, although it is still an Echani product and is therefore well suited to quick-moving combat.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "TRUE"
    },
    {
        "File name":  "ia_class6_003.png",
        "Icon":  "",
        "Name":  "Cinnagar War Suit",
        "Type":  "Armor",
        "Subtype":  "Medium",
        "Defense Rating":  "1d6",
        "Description":  "After the Great Hyperspace War a thousand years ago, the heirs of Empress Teta militarized their world and industry, a legacy that produced battle armor still sought after today.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "TRUE"
    },
    {
        "File name":  "ia_class6_004.png",
        "Icon":  "",
        "Name":  "Verpine Fiber Mesh",
        "Type":  "Armor",
        "Subtype":  "Medium",
        "Defense Rating":  "1d6",
        "Description":  "Raxsus Nuli had plans of planetary conquest in the wake of Sith aggression. Though eclipsed by recent events, the Jedi saw the pirate jailed and his Verpine stockpiles auctioned.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "TRUE"
    },
    {
        "File name":  "ia_class6_005.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor",
        "Subtype":  "Medium",
        "Defense Rating":  "1d6",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "TRUE"
    },
    {
        "File name":  "ia_class6_006.png",
        "Icon":  "",
        "Name":  "Exar Kun\u0027s Light Battle Suit",
        "Type":  "Armor",
        "Subtype":  "Medium",
        "Defense Rating":  "1d6",
        "Description":  "Attributed to Exar Kun, this armor may well have been one of those worn by the Dark Lord prior to his defeat forty years ago. He was rarely without considerable, yet flexible, personal armor.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "TRUE"
    },
    {
        "File name":  "ia_class6_007.png",
        "Icon":  "",
        "Name":  "Verpine Fiber Ultramesh",
        "Type":  "Armor",
        "Subtype":  "Medium",
        "Defense Rating":  "1d6 + 2",
        "Description":  "This Verpine combat suit is the most protective standard medium armor available, surpassing the defensive capabilities of most heavy armor.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "TRUE"
    },
    {
        "File name":  "ia_class6_008.png",
        "Icon":  "",
        "Name":  "Sith Battle Suit",
        "Type":  "Armor",
        "Subtype":  "Medium",
        "Defense Rating":  "1d6",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "TRUE"
    },
    {
        "File name":  "ia_class6_009.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor",
        "Subtype":  "Medium",
        "Defense Rating":  "1d6",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "TRUE"
    },
    {
        "File name":  "ia_class7_001.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor",
        "Subtype":  "Medium",
        "Defense Rating":  "1d8",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "TRUE"
    },
    {
        "File name":  "ia_class7_002.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor",
        "Subtype":  "Medium",
        "Defense Rating":  "1d8",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "TRUE"
    },
    {
        "File name":  "ia_class7_003.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor",
        "Subtype":  "Medium",
        "Defense Rating":  "1d8",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "TRUE"
    },
    {
        "File name":  "ia_class7_004.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor",
        "Subtype":  "Medium",
        "Defense Rating":  "1d8",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "TRUE"
    },
    {
        "File name":  "ia_class7_005.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor",
        "Subtype":  "Medium",
        "Defense Rating":  "1d8",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "TRUE"
    },
    {
        "File name":  "ia_class7_006.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor",
        "Subtype":  "Medium",
        "Defense Rating":  "1d8",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "TRUE"
    },
    {
        "File name":  "ia_class7_007.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor",
        "Subtype":  "Medium",
        "Defense Rating":  "1d8",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "TRUE"
    },
    {
        "File name":  "ia_class7_008.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor",
        "Subtype":  "Medium",
        "Defense Rating":  "1d8",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "TRUE"
    },
    {
        "File name":  "ia_class8_001.png",
        "Icon":  "",
        "Name":  "Battle Armor",
        "Type":  "Armor",
        "Subtype":  "Heavy",
        "Defense Rating":  "1d10",
        "Description":  "This isn\u0027t the heaviest of armor, but it comes close. Designed for heavy militias, it has the protection needed to keep a soldier alive during ranged combat with massive weapons.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "TRUE"
    },
    {
        "File name":  "ia_class8_002.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor",
        "Subtype":  "Heavy",
        "Defense Rating":  "1d10",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "TRUE"
    },
    {
        "File name":  "ia_class8_003.png",
        "Icon":  "",
        "Name":  "Corellian Powersuit",
        "Type":  "Armor",
        "Subtype":  "Heavy",
        "Defense Rating":  "1d10",
        "Description":  "Essentially an improved version of powered battle armor, the powersuit employs a system of servomotors to enhance the wearer\u0027s strength.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "TRUE"
    },
    {
        "File name":  "ia_class8_004.png",
        "Icon":  "",
        "Name":  "Echani Heavy Armor",
        "Type":  "Armor",
        "Subtype":  "Heavy",
        "Defense Rating":  "1d10",
        "Description":  "Echani Heavy Armor is comparable to typical heavy battle armor in terms of protection, but allows for slightly more mobility.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "TRUE"
    },
    {
        "File name":  "ia_class8_005.png",
        "Icon":  "",
        "Name":  "Verpine Zal Alloy Mesh",
        "Type":  "Armor",
        "Subtype":  "Heavy",
        "Defense Rating":  "1d10",
        "Description":  "Using the highly expensive Zal alloy, the Verpine have developed a suit without peer. The only thing greater than the protective capabilities of this armor is the price.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "TRUE"
    },
    {
        "File name":  "ia_class8_006.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor",
        "Subtype":  "Heavy",
        "Defense Rating":  "1d10",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "TRUE"
    },
    {
        "File name":  "ia_class8_007.png",
        "Icon":  "",
        "Name":  "Iotran Braceman Armor",
        "Type":  "Armor",
        "Subtype":  "Heavy",
        "Defense Rating":  "1d10",
        "Description":  "\nThe Iotran are a militaristic species from the industrial planet of Iotra on the Outer Rim. Their versatile armor is a favorite among experienced bounty hunters.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "TRUE"
    },
    {
        "File name":  "ia_class9_001.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor",
        "Subtype":  "Heavy",
        "Defense Rating":  "1d12",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "TRUE",
        "Restricts Force Powers":  "TRUE"
    },
    {
        "File name":  "ia_class9_002.png",
        "Icon":  "",
        "Name":  "Durasteel Heavy Armor",
        "Type":  "Armor",
        "Subtype":  "Heavy",
        "Defense Rating":  "1d12",
        "Description":  "Battle armor production thrived on Bonadan as the Republic recovered from war. This model heavy durasteel casing provides superior protection when compared to normal Heavy Battle Armor.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "TRUE",
        "Restricts Force Powers":  "TRUE"
    },
    {
        "File name":  "ia_class9_003.png",
        "Icon":  "",
        "Name":  "Mandalorian Battle Armor",
        "Type":  "Armor",
        "Subtype":  "Heavy",
        "Defense Rating":  "1d12",
        "Description":  "Republic soldiers saw this armor all too often during the Mandalorian War. It\u0027s understandable that the conflict could drag on when a fanatical enemy is so defensively outfitted.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "TRUE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "TRUE",
        "Restricts Force Powers":  "TRUE"
    },
    {
        "File name":  "ia_class9_004.png",
        "Icon":  "",
        "Name":  "Mandalorian Heavy Armor",
        "Type":  "Armor",
        "Subtype":  "Heavy",
        "Defense Rating":  "1d12",
        "Description":  "This armor is reserved for respected veteran Mandalorians. Immensely sturdy, stabilizers diffuse energy throughout the frame, shielding the wearer from disorienting impacts.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "TRUE",
        "Restricts Force Powers":  "TRUE"
    },
    {
        "File name":  "ia_class9_005.png",
        "Icon":  "",
        "Name":  "Felenar Armor",
        "Type":  "Armor",
        "Subtype":  "Heavy",
        "Defense Rating":  "1d12",
        "Description":  "This flexible armor is made of a variety of exotic minerals. Markings suggest that it was created by a species called the Felenar.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "TRUE",
        "Restricts Force Powers":  "TRUE"
    },
    {
        "File name":  "ia_class9_006.png",
        "Icon":  "",
        "Name":  "Matrix Armor",
        "Type":  "Armor",
        "Subtype":  "Heavy",
        "Defense Rating":  "1d12",
        "Description":  "Matrix armor is typically used for starship plating. Adapting it to personal use is expensive and technologically difficult. The armor is particularly resistant to blaster fire.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "TRUE",
        "Restricts Force Powers":  "TRUE"
    },
    {
        "File name":  "ia_class9_007.png",
        "Icon":  "",
        "Name":  "Mandalorian Assault Armor",
        "Type":  "Armor",
        "Subtype":  "Heavy",
        "Defense Rating":  "1d12",
        "Description":  "This was the armor of the Mandalorian elite frontline troops, a sight that Republic soldiers were all too familiar with during the war.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "TRUE",
        "Restricts Force Powers":  "TRUE"
    },
    {
        "File name":  "ia_class9_008.png",
        "Icon":  "",
        "Name":  "Flex Heavy Armor",
        "Type":  "Armor",
        "Subtype":  "Heavy",
        "Defense Rating":  "1d12",
        "Description":  "Flex Heavy Armor allows for greater mobility than even some medium armor. The primary alloy is still durasteel, but it is treated in methods that are poorly understood by most in the Republic. In fact, it is unclear who manufactures these rare suits of armor.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "TRUE"
    },
    {
        "File name":  "ia_classflt_001.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor",
        "Subtype":  "Light",
        "Defense Rating":  "1d4",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "TRUE"
    },
    {
        "File name":  "ia_classflt_002.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor",
        "Subtype":  "Light",
        "Defense Rating":  "1d4",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "TRUE"
    },
    {
        "File name":  "ia_classflt_003.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor",
        "Subtype":  "Light",
        "Defense Rating":  "1d4",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "TRUE"
    },
    {
        "File name":  "ia_classzs_001.png",
        "Icon":  "",
        "Name":  "Zeison Sha Warrior Armor",
        "Type":  "Armor",
        "Subtype":  "Light",
        "Defense Rating":  "1d4",
        "Description":  "Zeison Sha Warriors are powerful combatants who are particularly skilled in telekenetic Force Powers. Their fortified garments are somewhat restrictive, but do not interfere with their use of the Force. They can be upgraded with some underlays.\n \nThe Outer Rim planet Yanibar was the home of the Zeison Sha, who developed their Force powers as a means of surviving the harsh planet. Zeison Sha stress independence and survival as well as assistance to those in need.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "TRUE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ia_classzs_002.png",
        "Icon":  "",
        "Name":  "Zeison Sha Initiate Armor",
        "Type":  "Armor",
        "Subtype":  "Light",
        "Defense Rating":  "1d4",
        "Description":  "Zeison Sha initiates are known for their survival skills and resourcefulness. Their flexible armor is very durable and can be upgraded with some underlays.\n \nThe Outer Rim planet Yanibar was the home of the Zeison Sha, who developed their Force powers as a means of surviving the harsh planet. Zeison Sha stress independence and survival as well as assistance to those in need.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "TRUE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ia_classzs_003.png",
        "Icon":  "",
        "Name":  "Jal Shey Neophyte Armor",
        "Type":  "Armor",
        "Subtype":  "Light",
        "Defense Rating":  "1d4",
        "Description":  "Jal Shey neophytes have begun their lifelong quest to understand the nature of the Force. Their light armor carries with it an aura of dignity and competence.\n \nThe Jal Shey concentrate on intellectual study of the Force, seeking to understand it at a mental level, rather than a spiritual one. Jal Shey are typically exceptional diplomats, but are less successful in physical pursuits.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "TRUE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ia_classzs_004.png",
        "Icon":  "",
        "Name":  "Jal Shey Advisor Armor",
        "Type":  "Armor",
        "Subtype":  "Light",
        "Defense Rating":  "1d4",
        "Description":  "Jal Shey advisors possess a strong understanding of the Force and are widely respected for their wisdom.\n \nThe Jal Shey concentrate on intellectual study of the Force, seeking to understand it at a mental level, rather than a spiritual one. Jal Shey are typically exceptional diplomats, but are less successful in physical pursuits.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "TRUE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ia_classzs_005.png",
        "Icon":  "",
        "Name":  "Darth Malak\u0027s Armor",
        "Type":  "Armor",
        "Subtype":  "Light",
        "Defense Rating":  "1d4",
        "Description":  "It is believed that Darth Malak, the fallen former apprentice of Darth Revan, once possessed this garment. Malak and Revan are credited with starting the Jedi Civil War, which led to the collapse of the Jedi Order.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "TRUE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ia_classzs_006.png",
        "Icon":  "",
        "Name":  "Jal Shey Mentor Armor",
        "Type":  "Armor",
        "Subtype":  "Light",
        "Defense Rating":  "1d4",
        "Description":  "Jal Shey mentors are unparalleled in their intellect and often serve as highly respected advisors and teachers.\n \nThe Jal Shey concentrate on intellectual study of the Force, seeking to understand it at a mental level, rather than a spiritual one. Jal Shey are typically exceptional diplomats, but are less successful in physical pursuits.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "TRUE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ia_cloths_001.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor",
        "Subtype":  "Clothes",
        "Defense Rating":  "0",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ia_cloths_002.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor",
        "Subtype":  "Clothes",
        "Defense Rating":  "0",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ia_cloths_003.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor",
        "Subtype":  "Clothes",
        "Defense Rating":  "0",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ia_cloths_004.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor",
        "Subtype":  "Clothes",
        "Defense Rating":  "0",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ia_cloths_005.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor",
        "Subtype":  "Clothes",
        "Defense Rating":  "0",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ia_cloths_006.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor",
        "Subtype":  "Clothes",
        "Defense Rating":  "0",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ia_cloths_007.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor",
        "Subtype":  "Clothes",
        "Defense Rating":  "0",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ia_cloths_008.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor",
        "Subtype":  "Clothes",
        "Defense Rating":  "0",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ia_cloths_009.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor",
        "Subtype":  "Clothes",
        "Defense Rating":  "0",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ia_disguise_001.png",
        "Icon":  "",
        "Name":  "Sith Trooper Armor",
        "Type":  "Armor",
        "Subtype":  "Armor",
        "Defense Rating":  "0",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "FALSE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "TRUE"
    },
    {
        "File name":  "ia_disguise_002.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor",
        "Subtype":  "Armor",
        "Defense Rating":  "0",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "FALSE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "TRUE"
    },
    {
        "File name":  "ia_jedirobe_001.png",
        "Icon":  "",
        "Name":  "Padawan Robe",
        "Type":  "Armor",
        "Subtype":  "Robe",
        "Defense Rating":  "0",
        "Description":  "Members of the Jedi Order typically wear plain or unassuming garments.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "TRUE",
        "Upgradeable Underlay":  "FALSE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ia_jedirobe_002.png",
        "Icon":  "",
        "Name":  "Jolee\u0027s Robe",
        "Type":  "Armor",
        "Subtype":  "Robe",
        "Defense Rating":  "0",
        "Description":  "Jolee Bindo remained outside of the Jedi Order in his pursuit of knowledge. These powerful, yet unassuming robes were believed to have been owned by him, though his current whereabouts is unknown.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "FALSE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ia_jedirobe_003.png",
        "Icon":  "",
        "Name":  "Dark Padawan Robe",
        "Type":  "Armor",
        "Subtype":  "Robe",
        "Defense Rating":  "0",
        "Description":  "These are simple robes, kept modest not by a desire to appear humble, but to offer the greatest freedom of movement during battle.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "FALSE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ia_jedirobe_004.png",
        "Icon":  "",
        "Name":  "Jedi Robe",
        "Type":  "Armor",
        "Subtype":  "Robe",
        "Defense Rating":  "0",
        "Description":  "Members of the Jedi Order typically wear plain or unassuming garments.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "TRUE",
        "Upgradeable Underlay":  "FALSE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ia_jedirobe_005.png",
        "Icon":  "",
        "Name":  "Exile\u0027s Robe",
        "Type":  "Armor",
        "Subtype":  "Robe",
        "Defense Rating":  "0",
        "Description":  "Unassuming garment of an exiled Jedi.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "FALSE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ia_jedirobe_006.png",
        "Icon":  "",
        "Name":  "Dark Jedi Robe",
        "Type":  "Armor",
        "Subtype":  "Robe",
        "Defense Rating":  "0",
        "Description":  "These are simple robes, kept modest not by a desire to appear humble, but to offer the greatest freedom of movement during battle.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "FALSE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ia_jedirobe_007.png",
        "Icon":  "",
        "Name":  "Baran Do Novice Robe",
        "Type":  "Armor",
        "Subtype":  "Robe",
        "Defense Rating":  "0",
        "Description":  "Novices are those who have begun their training in the Baran Do philosophy, learning how to empty their minds and find tranquility in any situation.\n \nThe Baran Do are force sensitive members of the Kel Dor race. They seek inner peace and are very patient, consulting with the Force before making decisions.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "FALSE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ia_jedirobe_008.png",
        "Icon":  "",
        "Name":  "Ossus Keeper Robe",
        "Type":  "Armor",
        "Subtype":  "Robe",
        "Defense Rating":  "0",
        "Description":  "The Keepers of the Hall of Knowledge in the Great Jedi Library maintained the protected archives and acted as references to those who desired a more interactive solution to the their problems.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "FALSE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ia_jedirobe_009.png",
        "Icon":  "",
        "Name":  "Norris Robe",
        "Type":  "Armor",
        "Subtype":  "Robe",
        "Defense Rating":  "0",
        "Description":  "Stained with pigments from the beautiful and rare norris root found on the planet Almar, these robes are naturally resistant to energy.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "FALSE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ia_jedirobe_010.png",
        "Icon":  "",
        "Name":  "Baran Do Sage Robe",
        "Type":  "Armor",
        "Subtype":  "Robe",
        "Defense Rating":  "0",
        "Description":  "Baran Do Sages are the most elite of their order, able to see into the future, the past, and across the entire galaxy.\n \nThe Baran Do are force sensitive members of the Kel Dor race. They seek inner peace and are very patient, consulting with the Force before making decisions.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "FALSE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ia_kghtrobe_001.png",
        "Icon":  "",
        "Name":  "Brown Tunic",
        "Type":  "Armor",
        "Subtype":  "Robe",
        "Defense Rating":  "0",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "FALSE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ia_kghtrobe_002.png",
        "Icon":  "",
        "Name":  "Grey Tunic",
        "Type":  "Armor",
        "Subtype":  "Robe",
        "Defense Rating":  "0",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "FALSE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ia_kghtrobe_003.png",
        "Icon":  "",
        "Name":  "Orange Tunic",
        "Type":  "Armor",
        "Subtype":  "Robe",
        "Defense Rating":  "0",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "FALSE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ia_kghtrobe_004.png",
        "Icon":  "",
        "Name":  "Blue Tunic",
        "Type":  "Armor",
        "Subtype":  "Robe",
        "Defense Rating":  "0",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "FALSE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ia_mstrrobe_001.png",
        "Icon":  "",
        "Name":  "Jedi Knight Robe",
        "Type":  "Armor",
        "Subtype":  "Robe",
        "Defense Rating":  "0",
        "Description":  "Members of the Order typically wear plain or unassuming garments, but this variant offers the additional protection needed by Jedi influencing important events.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ia_mstrrobe_002.png",
        "Icon":  "",
        "Name":  "Sylvar\u0027s Robe",
        "Type":  "Armor",
        "Subtype":  "Robe",
        "Defense Rating":  "0",
        "Description":  "Sylvar was a fellow student of Exar Kun and the wife of the fallen Jedi Crado, who fell to Kun\u0027s side during the Sith War many decades past. Despite several major trials, Sylvar ultimately remained true to the light side and was a strong voice in the Jedi Order.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ia_mstrrobe_003.png",
        "Icon":  "",
        "Name":  "Crado\u0027s Robe",
        "Type":  "Armor",
        "Subtype":  "Robe",
        "Defense Rating":  "0",
        "Description":  "Crado was a Jedi who fell to the power of the dark side through the mighty Exar Kun. Crado betrayed his beloved Sylvar and was ultimately obliterated when the Cron Cluster was destroyed.\n \nGiven how completely Crado was killed, it is questionable whether this robe ever actually belonged to him. Regardless, this garment clearly eminates the power and corruption of the dark side.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ia_mstrrobe_004.png",
        "Icon":  "",
        "Name":  "Dark Jedi Knight Robe",
        "Type":  "Armor",
        "Subtype":  "Robe",
        "Defense Rating":  "0",
        "Description":  "Designed for those who relish personal combat, and know that power comes to those who take it, these robes offer good protection with no hindrance to movement.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ia_mstrrobe_005.png",
        "Icon":  "",
        "Name":  "Gray Jedi Robe",
        "Type":  "Armor",
        "Subtype":  "Robe",
        "Defense Rating":  "0",
        "Description":  "Gray Jedi are those who, though having completed the teachings of the Jedi, operate independently and outside of the Jedi Council. They are typically seen as misguided, though they have not necessarily succumbed to the dark side.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ia_mstrrobe_006.png",
        "Icon":  "",
        "Name":  "Jedi Master Robe",
        "Type":  "Armor",
        "Subtype":  "Robe",
        "Defense Rating":  "0",
        "Description":  "Members of the Order typically wear plain or unassuming garments, but Jedi Masters also know the importance of adequate protection when great challenges must be surmounted.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ia_mstrrobe_007.png",
        "Icon":  "",
        "Name":  "Natth Cowling",
        "Type":  "Armor",
        "Subtype":  "Robe",
        "Defense Rating":  "0",
        "Description":  "Dyed with water from the tainted Lake Natth on Ambria, these robes infuse the wearer a trace of the dark powers contained within the lake.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ia_mstrrobe_008.png",
        "Icon":  "",
        "Name":  "Thon\u0027s Robe",
        "Type":  "Armor",
        "Subtype":  "Robe",
        "Defense Rating":  "0",
        "Description":  "Thon was an enigmatic Jedi Watchman who kept even his species secret. He was a powerful agent of the light side and also trained many Jedi.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ia_mstrrobe_009.png",
        "Icon":  "",
        "Name":  "Handmaiden\u0027s Robe",
        "Type":  "Armor",
        "Subtype":  "Robe",
        "Defense Rating":  "0",
        "Description":  "This robe once belonged to the Handmaiden\u0027s mother, Arren. It is the only thing of hers the Handmaiden possesses.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ia_mstrrobe_010.png",
        "Icon":  "",
        "Name":  "Dark Jedi Master Robe",
        "Type":  "Armor",
        "Subtype":  "Robe",
        "Defense Rating":  "0",
        "Description":  "These robes offer superior protection while still allowing full freedom of movement. They are the robes of the true masters, those whose will and authority go unopposed.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ia_mstrrobe_011.png",
        "Icon":  "",
        "Name":  "Aleema Keto\u0027s Robe",
        "Type":  "Armor",
        "Subtype":  "Robe",
        "Defense Rating":  "0",
        "Description":  "Aleema Keto began her training as a Jedi, but while researching the Sith became enthralled by their power and fell to the dark side. She was a master of illusions and helped seduce Ulic Qel-Droma to the dark side.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ia_mstrrobe_012.png",
        "Icon":  "",
        "Name":  "Matukai Adept Robe",
        "Type":  "Armor",
        "Subtype":  "Robe",
        "Defense Rating":  "0",
        "Description":  "Matukai adepts are masters at guiding their bodies with the Force. They are capable of astounding physical feats.\n \nThe Matukai are a group of Force sensitives who use their physical body to channel the Force. The balance of the physical and spiritual is a cornerstone of their philosophy.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ia_mstrrobe_013.png",
        "Icon":  "",
        "Name":  "Matukai Apprentice Robe",
        "Type":  "Armor",
        "Subtype":  "Robe",
        "Defense Rating":  "0",
        "Description":  "Matukai apprentices master physical meditation by practicing martial arts techniques. Their robes are designed to help them achieve harmony between the mind and body.\n \nThe Matukai are a group of Force sensitives who use their physical body to channel the Force. The balance of the physical and spiritual is a cornerstone of their philosophy.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ia_mstrrobe_014.png",
        "Icon":  "",
        "Name":  "Nomi\u0027s Robe",
        "Type":  "Armor",
        "Subtype":  "Robe",
        "Defense Rating":  "0",
        "Description":  "Nomi displayed incredible affinity for the Force, but only reluctantly pursued Jedi training following the death of her husband, Andur. She became one of the greatest Jedi of the time, training under Master Thon.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ia_mstrrobe_015.png",
        "Icon":  "",
        "Name":  "Arca Jeth\u0027s Robe",
        "Type":  "Armor",
        "Subtype":  "Robe",
        "Defense Rating":  "0",
        "Description":  "Arca Jeth was a powerful Arkanian Jedi Master who was killed in the Great Sith War. His spirit helped provide guidance to Ulic Qel-Droma.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ia_revan_001.png",
        "Icon":  "",
        "Name":  "Revan\u0027s Robe",
        "Type":  "Armor",
        "Subtype":  "Robe",
        "Defense Rating":  "1d4",
        "Description":  "Created by the mystical technology of the Star Forge, these robes focus the dark side energies of the wearer, fueling their power. The Sith Lord Darth Revan was wearing similar robes when captured by the Jedi, who viewed the garments as an abomination and destroyed them. However the Jedi Council, not being familiar with the origins of the robes, were unaware that the Star Forge would be capable of producing an item of such terrible power a second time.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "TRUE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ia_revan_002.png",
        "Icon":  "",
        "Name":  "Starforge Robe",
        "Type":  "Armor",
        "Subtype":  "Robe",
        "Defense Rating":  "1d4",
        "Description":  "Created by the mystical technology of the Star Forge, these robes focus the inherent Force abilities of the wearer, fueling their power. Although the Star Forge itself is an artifact of the dark side, these robes were customized using an analysis of the Jedi they were created for, resulting in a powerful light side item that the Jedi can safely use against their enemies without fear of taint or corruption.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "TRUE",
        "Upgradeable Underlay":  "TRUE",
        "Upgradable Overlay":  "TRUE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ia_slave_001.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor",
        "Subtype":  "Clothes",
        "Defense Rating":  "0",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "FALSE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ii_frarmbnds_001.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Shield",
        "Subtype":  "",
        "Defense Rating":  "0",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "FALSE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ii_frarmbnds_002.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Shield",
        "Subtype":  "",
        "Defense Rating":  "0",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "FALSE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ii_frarmbnds_003.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Shield",
        "Subtype":  "",
        "Defense Rating":  "0",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "FALSE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ii_frarmbnds_004.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Shield",
        "Subtype":  "",
        "Defense Rating":  "0",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "FALSE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ii_frarmbnds_005.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Shield",
        "Subtype":  "",
        "Defense Rating":  "0",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "FALSE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ii_frarmbnds_006.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Shield",
        "Subtype":  "",
        "Defense Rating":  "0",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "FALSE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ii_frarmbnds_007.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Shield",
        "Subtype":  "",
        "Defense Rating":  "0",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "FALSE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ii_frarmbnds_008.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Shield",
        "Subtype":  "",
        "Defense Rating":  "0",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "FALSE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ii_frarmbnds_009.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Shield",
        "Subtype":  "",
        "Defense Rating":  "0",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "FALSE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ii_frarmbnds_010.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Shield",
        "Subtype":  "",
        "Defense Rating":  "0",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "FALSE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ii_gauntlet_001.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Gloves",
        "Subtype":  "",
        "Defense Rating":  "0",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "FALSE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ii_gauntlet_002.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Gloves",
        "Subtype":  "",
        "Defense Rating":  "0",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "FALSE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ii_gauntlet_003.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Gloves",
        "Subtype":  "",
        "Defense Rating":  "0",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "FALSE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ii_gauntlet_004.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Gloves",
        "Subtype":  "",
        "Defense Rating":  "0",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "FALSE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ii_gauntlet_005.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Gloves",
        "Subtype":  "",
        "Defense Rating":  "0",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "FALSE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ii_gauntlet_006.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Gloves",
        "Subtype":  "",
        "Defense Rating":  "0",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "FALSE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ii_gauntlet_007.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Gloves",
        "Subtype":  "",
        "Defense Rating":  "0",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "FALSE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ii_gauntlet_008.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Gloves",
        "Subtype":  "",
        "Defense Rating":  "0",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "FALSE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ii_gauntlet_009.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Gloves",
        "Subtype":  "",
        "Defense Rating":  "0",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "FALSE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ii_gauntlet_010.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Gloves",
        "Subtype":  "",
        "Defense Rating":  "0",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "FALSE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ii_gauntlet_011.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Gloves",
        "Subtype":  "",
        "Defense Rating":  "0",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "FALSE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ii_gauntlet_012.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Gloves",
        "Subtype":  "",
        "Defense Rating":  "0",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "FALSE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ii_gauntlet_013.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Gloves",
        "Subtype":  "",
        "Defense Rating":  "0",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "FALSE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ii_gauntlet_014.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Gloves",
        "Subtype":  "",
        "Defense Rating":  "0",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "FALSE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ii_belt_001.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Belt",
        "Subtype":  "",
        "Defense Rating":  "0",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "FALSE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ii_belt_002.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Belt",
        "Subtype":  "",
        "Defense Rating":  "0",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "FALSE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ii_belt_003.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Belt",
        "Subtype":  "",
        "Defense Rating":  "0",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "FALSE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ii_belt_004.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Belt",
        "Subtype":  "",
        "Defense Rating":  "0",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "FALSE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ii_belt_005.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Belt",
        "Subtype":  "",
        "Defense Rating":  "0",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "FALSE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ii_belt_006.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Belt",
        "Subtype":  "",
        "Defense Rating":  "0",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "FALSE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ii_belt_007.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Belt",
        "Subtype":  "",
        "Defense Rating":  "0",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "FALSE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ii_belt_008.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Belt",
        "Subtype":  "",
        "Defense Rating":  "0",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "FALSE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ii_belt_009.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Belt",
        "Subtype":  "",
        "Defense Rating":  "0",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "FALSE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ii_belt_010.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Belt",
        "Subtype":  "",
        "Defense Rating":  "0",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "FALSE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ii_belt_011.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Belt",
        "Subtype":  "",
        "Defense Rating":  "0",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "FALSE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ii_belt_012.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Belt",
        "Subtype":  "",
        "Defense Rating":  "0",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "FALSE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ii_belt_013.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Belt",
        "Subtype":  "",
        "Defense Rating":  "0",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "FALSE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ii_belt_014.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Belt",
        "Subtype":  "",
        "Defense Rating":  "0",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "FALSE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ii_belt_015.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Belt",
        "Subtype":  "",
        "Defense Rating":  "0",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "FALSE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ii_mask_001.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Headgear",
        "Subtype":  "",
        "Defense Rating":  "0",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "FALSE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ii_mask_002.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Headgear",
        "Subtype":  "",
        "Defense Rating":  "0",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "FALSE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ii_mask_003.png",
        "Icon":  "",
        "Name":  "Absorption Visor",
        "Type":  "Headgear",
        "Subtype":  "",
        "Defense Rating":  "0",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "FALSE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ii_mask_004.png",
        "Icon":  "",
        "Name":  "Bothan Sensory Visor",
        "Type":  "Headgear",
        "Subtype":  "",
        "Defense Rating":  "0",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "FALSE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ii_mask_005.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Headgear",
        "Subtype":  "",
        "Defense Rating":  "0",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "FALSE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ii_mask_006.png",
        "Icon":  "",
        "Name":  "Breath Mask",
        "Type":  "Headgear",
        "Subtype":  "Breathing",
        "Defense Rating":  "0",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "FALSE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ii_mask_007.png",
        "Icon":  "",
        "Name":  "Bothan Perception Visor",
        "Type":  "Headgear",
        "Subtype":  "",
        "Defense Rating":  "0",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "FALSE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ii_mask_008.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Headgear",
        "Subtype":  "",
        "Defense Rating":  "0",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "FALSE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ii_mask_009.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Headgear",
        "Subtype":  "",
        "Defense Rating":  "0",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "FALSE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ii_mask_010.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Headgear",
        "Subtype":  "Breathing",
        "Defense Rating":  "0",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "FALSE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ii_mask_011.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Headgear",
        "Subtype":  "",
        "Defense Rating":  "0",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "FALSE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ii_mask_012.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Headgear",
        "Subtype":  "Breathing",
        "Defense Rating":  "0",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "FALSE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ii_mask_013.png",
        "Icon":  "",
        "Name":  "Das\u0027skar Hunting Mask",
        "Type":  "Headgear",
        "Subtype":  "",
        "Defense Rating":  "0",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "FALSE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ii_mask_014.png",
        "Icon":  "",
        "Name":  "Circlet of Saresh",
        "Type":  "Headgear",
        "Subtype":  "",
        "Defense Rating":  "0",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "FALSE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_251.png",
        "Icon":  "",
        "Name":  "Nihilus\u0027 mask",
        "Type":  "Headgear",
        "Subtype":  "",
        "Defense Rating":  "0",
        "Description":  "It is the last surviving piece of the beast who died and was reborn in the shattered world of Malachor V.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "TRUE",
        "Upgradeable Underlay":  "FALSE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_011.png",
        "Icon":  "",
        "Name":  "Mandalorian Helmet",
        "Type":  "Headgear",
        "Subtype":  "Breathing",
        "Defense Rating":  "0",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "FALSE",
        "Upgradeable Underlay":  "FALSE",
        "Upgradable Overlay":  "FALSE",
        "Restricts Force Powers":  "FALSE"
    }
];
