window.appData = window.appData || {};
window.appData.feats = [
    {
        "File name":  "ifrm_force01.png",
        "Icon":  "",
        "Name":  "Force Channel",
        "Type":  "Feat",
        "Subtype":  "Form",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "5",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ifrm_force02.png",
        "Icon":  "",
        "Name":  "Force Affinity",
        "Type":  "Feat",
        "Subtype":  "Form",
        "Description":  "",
        "Prerequisite":  "Force Channel",
        "Cost":  "10",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ifrm_force03.png",
        "Icon":  "",
        "Name":  "Force Potency",
        "Type":  "Feat",
        "Subtype":  "Form",
        "Description":  "",
        "Prerequisite":  "Force Affinity",
        "Cost":  "15",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ifrm_force04.png",
        "Icon":  "",
        "Name":  "Force Mastery",
        "Type":  "Feat",
        "Subtype":  "Form",
        "Description":  "",
        "Prerequisite":  "Force Potency",
        "Cost":  "20",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ifrm_saber01.png",
        "Icon":  "",
        "Name":  "Form I: Shii-Cho (Determination)",
        "Type":  "Feat",
        "Subtype":  "Form",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "5",
        "Visible":  "TRUE"
    },
    {
        "File name":  "ifrm_saber01.png",
        "Icon":  "",
        "Name":  "Affinity: Form I: Shii-Cho (Determination)",
        "Type":  "Feat",
        "Subtype":  "Form",
        "Description":  "",
        "Prerequisite":  "Form I: Shii-Cho (Determination)",
        "Cost":  "10",
        "Visible":  "TRUE"
    },
    {
        "File name":  "ifrm_saber01.png",
        "Icon":  "",
        "Name":  "Mastery: Form I: Shii-Cho (Determination)",
        "Type":  "Feat",
        "Subtype":  "Form",
        "Description":  "",
        "Prerequisite":  "Affinity: Form I: Shii-Cho (Determination)",
        "Cost":  "15",
        "Visible":  "TRUE"
    },
    {
        "File name":  "ifrm_saber02.png",
        "Icon":  "",
        "Name":  "Form II: Makashi (Contention)",
        "Type":  "Feat",
        "Subtype":  "Form",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "5",
        "Visible":  "TRUE"
    },
    {
        "File name":  "ifrm_saber02.png",
        "Icon":  "",
        "Name":  "Affinity: Form II: Makashi (Contention)",
        "Type":  "Feat",
        "Subtype":  "Form",
        "Description":  "",
        "Prerequisite":  "Form II: Makashi (Contention)",
        "Cost":  "10",
        "Visible":  "TRUE"
    },
    {
        "File name":  "ifrm_saber02.png",
        "Icon":  "",
        "Name":  "Mastery: Form II: Makashi (Contention)",
        "Type":  "Feat",
        "Subtype":  "Form",
        "Description":  "",
        "Prerequisite":  "Affinity: Form II: Makashi (Contention)",
        "Cost":  "15",
        "Visible":  "TRUE"
    },
    {
        "File name":  "ifrm_saber03.png",
        "Icon":  "",
        "Name":  "Form III: Soresu (Resilience)",
        "Type":  "Feat",
        "Subtype":  "Form",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "5",
        "Visible":  "TRUE"
    },
    {
        "File name":  "ifrm_saber03.png",
        "Icon":  "",
        "Name":  "Affinity: Form III: Soresu (Resilience)",
        "Type":  "Feat",
        "Subtype":  "Form",
        "Description":  "",
        "Prerequisite":  "Form III: Soresu (Resilience)",
        "Cost":  "10",
        "Visible":  "TRUE"
    },
    {
        "File name":  "ifrm_saber03.png",
        "Icon":  "",
        "Name":  "Mastery: Form III: Soresu (Resilience)",
        "Type":  "Feat",
        "Subtype":  "Form",
        "Description":  "",
        "Prerequisite":  "Affinity: Form III: Soresu (Resilience)",
        "Cost":  "15",
        "Visible":  "TRUE"
    },
    {
        "File name":  "ifrm_saber04.png",
        "Icon":  "",
        "Name":  "Form IV: Ataru (Aggression)",
        "Type":  "Feat",
        "Subtype":  "Form",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "5",
        "Visible":  "TRUE"
    },
    {
        "File name":  "ifrm_saber04.png",
        "Icon":  "",
        "Name":  "Affinity: Form IV: Ataru (Aggression)",
        "Type":  "Feat",
        "Subtype":  "Form",
        "Description":  "",
        "Prerequisite":  "Form IV: Ataru (Aggression)",
        "Cost":  "10",
        "Visible":  "TRUE"
    },
    {
        "File name":  "ifrm_saber04.png",
        "Icon":  "",
        "Name":  "Mastery: Form IV: Ataru (Aggression)",
        "Type":  "Feat",
        "Subtype":  "Form",
        "Description":  "",
        "Prerequisite":  "Affinity: Form IV: Ataru (Aggression)",
        "Cost":  "15",
        "Visible":  "TRUE"
    },
    {
        "File name":  "ifrm_saber05.png",
        "Icon":  "",
        "Name":  "Form V: Shien (Perseverance)",
        "Type":  "Feat",
        "Subtype":  "Form",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "5",
        "Visible":  "TRUE"
    },
    {
        "File name":  "ifrm_saber05.png",
        "Icon":  "",
        "Name":  "Affinity: Form V: Shien (Perseverance)",
        "Type":  "Feat",
        "Subtype":  "Form",
        "Description":  "",
        "Prerequisite":  "Form V: Shien (Perseverance)",
        "Cost":  "10",
        "Visible":  "TRUE"
    },
    {
        "File name":  "ifrm_saber05.png",
        "Icon":  "",
        "Name":  "Mastery: Form V: Shien (Perseverance)",
        "Type":  "Feat",
        "Subtype":  "Form",
        "Description":  "",
        "Prerequisite":  "Affinity: Form V: Shien (Perseverance)",
        "Cost":  "15",
        "Visible":  "TRUE"
    },
    {
        "File name":  "ifrm_saber06.png",
        "Icon":  "",
        "Name":  "Form VI: Niman (Moderation)",
        "Type":  "Feat",
        "Subtype":  "Form",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "5",
        "Visible":  "TRUE"
    },
    {
        "File name":  "ifrm_saber06.png",
        "Icon":  "",
        "Name":  "Affinity: Form VI: Niman (Moderation)",
        "Type":  "Feat",
        "Subtype":  "Form",
        "Description":  "",
        "Prerequisite":  "Form VI: Niman (Moderation)",
        "Cost":  "10",
        "Visible":  "TRUE"
    },
    {
        "File name":  "ifrm_saber06.png",
        "Icon":  "",
        "Name":  "Mastery: Form VI: Niman (Moderation)",
        "Type":  "Feat",
        "Subtype":  "Form",
        "Description":  "",
        "Prerequisite":  "Affinity: Form VI: Niman (Moderation)",
        "Cost":  "15",
        "Visible":  "TRUE"
    },
    {
        "File name":  "ifrm_saber07.png",
        "Icon":  "",
        "Name":  "Form VII: Juyo (Ferocity)",
        "Type":  "Feat",
        "Subtype":  "Form",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "5",
        "Visible":  "TRUE"
    },
    {
        "File name":  "ifrm_saber07.png",
        "Icon":  "",
        "Name":  "Affinity: Form VII: Juyo (Ferocity)",
        "Type":  "Feat",
        "Subtype":  "Form",
        "Description":  "",
        "Prerequisite":  "Form VII: Juyo (Ferocity)",
        "Cost":  "10",
        "Visible":  "TRUE"
    },
    {
        "File name":  "ifrm_saber07.png",
        "Icon":  "",
        "Name":  "Mastery: Form VII: Juyo (Ferocity)",
        "Type":  "Feat",
        "Subtype":  "Form",
        "Description":  "",
        "Prerequisite":  "Affinity: Form VII: Juyo (Ferocity)",
        "Cost":  "15",
        "Visible":  "TRUE"
    },
    {
        "File name":  "if_2weap01.png",
        "Icon":  "",
        "Name":  "Two-Weapon Fighting",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "5",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_2weap02.png",
        "Icon":  "",
        "Name":  "Improved Two-Weapon Fighting",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Two-Weapon Fighting",
        "Cost":  "10",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_2weap03.png",
        "Icon":  "",
        "Name":  "Master Two-Weapon Fighting",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Improved Two-Weapon Fighting",
        "Cost":  "15",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_armprof01.png",
        "Icon":  "",
        "Name":  "Armor Proficiency Light",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "5",
        "Visible":  "TRUE"
    },
    {
        "File name":  "if_armprof02.png",
        "Icon":  "",
        "Name":  "Armor Proficiency Medium",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Armor Proficiency Light",
        "Cost":  "10",
        "Visible":  "TRUE"
    },
    {
        "File name":  "if_armprof03.png",
        "Icon":  "",
        "Name":  "Armor Proficiency Heavy",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Armor Proficiency Medium",
        "Cost":  "15",
        "Visible":  "TRUE"
    },
    {
        "File name":  "if_assassin01.png",
        "Icon":  "",
        "Name":  "Assassin Protocols",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "5",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_assassin02.png",
        "Icon":  "",
        "Name":  "Modified Assassin Protocols",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Assassin Protocols",
        "Cost":  "10",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_assassin03.png",
        "Icon":  "",
        "Name":  "Integrated Assassin Protocols",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Modified Assassin Protocols",
        "Cost":  "15",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_battlemed.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Feat",
        "Subtype":  "Power",
        "Description":  "Not needed?",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_blastint.png",
        "Icon":  "",
        "Name":  "Blaster Integration",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "This feat grants Expert Droids the ability to integrate blasters into their frames to act as self-contained weapons systems. Special universal ports allow internal placement of most models of blaster pistol, tapping the energy pack and emitters as though factory installed.",
        "Prerequisite":  "Droid",
        "Cost":  "5",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_cautious01.png",
        "Icon":  "",
        "Name":  "Caution",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "5",
        "Visible":  "TRUE"
    },
    {
        "File name":  "if_cautious02.png",
        "Icon":  "",
        "Name":  "Improved Caution",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Caution",
        "Cost":  "10",
        "Visible":  "TRUE"
    },
    {
        "File name":  "if_cautious03.png",
        "Icon":  "",
        "Name":  "Master Caution",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Improved Caution",
        "Cost":  "15",
        "Visible":  "TRUE"
    },
    {
        "File name":  "if_ccombat01.png",
        "Icon":  "",
        "Name":  "Close Combat",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "5",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_ccombat02.png",
        "Icon":  "",
        "Name":  "Improved Close Combat",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Close Combat",
        "Cost":  "10",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_clsskill01.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_clsskill02.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_clsskill03.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_clsskill04.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_clsskill05.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_clsskill06.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_clsskill07.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_craft.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_crtstrk01.png",
        "Icon":  "",
        "Name":  "Critical Strike",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "5",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_crtstrk02.png",
        "Icon":  "",
        "Name":  "Improved Critical Strike",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Critical Strike",
        "Cost":  "10",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_crtstrk03.png",
        "Icon":  "",
        "Name":  "Master Critical Strike",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Improved Critical Strike",
        "Cost":  "15",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_deflect.png",
        "Icon":  "",
        "Name":  "Deflect",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "?",
        "Cost":  "5",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_dodge01.png",
        "Icon":  "",
        "Name":  "Uncanny Dodge II",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "5",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_dodge02.png",
        "Icon":  "",
        "Name":  "Uncanny Dodge II",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Uncanny Dodge II",
        "Cost":  "10",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_drdinterf.png",
        "Icon":  "",
        "Name":  "Droid Interface",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "This feat gives the Droid the ability to speak with other droids who don\u0027t speak a sentient language. Granted to Expert Droids.\n\nThis feat can also be selected by a Combat Droid.",
        "Prerequisite":  "Droid",
        "Cost":  "5",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_droidac01.png",
        "Icon":  "",
        "Name":  "Logic Upgrade",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "5",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_droidac02.png",
        "Icon":  "",
        "Name":  "Logic Upgrade: Tactician",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Logic Upgrade",
        "Cost":  "10",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_droidac03.png",
        "Icon":  "",
        "Name":  "Logic Upgrade: Mastermind",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Logic Upgrade: Tactician",
        "Cost":  "15",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_droidup01.png",
        "Icon":  "",
        "Name":  "Class 1 Droid Upgrade",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "5",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_droidup02.png",
        "Icon":  "",
        "Name":  "Class 2 Droid Upgrade",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Class 1 Droid Upgrade",
        "Cost":  "10",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_droidup03.png",
        "Icon":  "",
        "Name":  "Class 3 Droid Upgrade",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Class 2 Droid Upgrade",
        "Cost":  "15",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_dscorrupt.png",
        "Icon":  "",
        "Name":  "Dark Side Corruption I",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_dscorrupt01.png",
        "Icon":  "",
        "Name":  "Dark Side Corruption II",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_dscorrupt02.png",
        "Icon":  "",
        "Name":  "Dark Side Corruption III",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_dscorrupt03.png",
        "Icon":  "",
        "Name":  "Dark Side Corruption IV",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_dualstrk01.png",
        "Icon":  "",
        "Name":  "Dual Strike",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "5",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_dualstrk02.png",
        "Icon":  "",
        "Name":  "Improved Dual Strike",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Dual Strike",
        "Cost":  "10",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_dualstrk03.png",
        "Icon":  "",
        "Name":  "Master Dual Strike",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Improved Dual Strike",
        "Cost":  "15",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_duel01.png",
        "Icon":  "",
        "Name":  "Dueling",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "5",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_duel02.png",
        "Icon":  "",
        "Name":  "Improved Dueling",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Dueling",
        "Cost":  "10",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_duel03.png",
        "Icon":  "",
        "Name":  "Master Dueling",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Improved Dueling",
        "Cost":  "15",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_echstrike01.png",
        "Icon":  "",
        "Name":  "Echani Strike",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "5",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_echstrike02.png",
        "Icon":  "",
        "Name":  "Improved Echani Strike",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Echani Strike",
        "Cost":  "10",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_echstrike03.png",
        "Icon":  "",
        "Name":  "Master Echani Strike",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Improved Echani Strike",
        "Cost":  "15",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_empathy01.png",
        "Icon":  "",
        "Name":  "Empathy",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "5",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_empathy02.png",
        "Icon":  "",
        "Name":  "Improved Empathy",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Empathy",
        "Cost":  "10",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_empathy03.png",
        "Icon":  "",
        "Name":  "Master Empathy",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Improved Empathy",
        "Cost":  "15",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_evasion.png",
        "Icon":  "",
        "Name":  "Evasion",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_finesse01.png",
        "Icon":  "",
        "Name":  "Finesse: Melee Weapons",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "5",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_finesse02.png",
        "Icon":  "",
        "Name":  "Finesse: Lightsabers",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Jedi",
        "Cost":  "10",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_flurry01.png",
        "Icon":  "",
        "Name":  "Flurry",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "5",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_flurry02.png",
        "Icon":  "",
        "Name":  "Improved Flurry",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Flurry",
        "Cost":  "10",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_flurry03.png",
        "Icon":  "",
        "Name":  "Master Flurry",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Improved Flurry",
        "Cost":  "15",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_focalter.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_focaware.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_focboost.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_foccomp.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_foccontr.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_focdemo.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_focmaster.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_focmed.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_focpers.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_focrepair.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_focsecur.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_focsense.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_focstlth.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_forcechain.png",
        "Icon":  "",
        "Name":  "Force Chain",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_forcesn.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_fortitude.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_frccamo01.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Feat",
        "Subtype":  "Power",
        "Description":  "Not needed?",
        "Prerequisite":  "",
        "Cost":  "5",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_frccamo02.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Feat",
        "Subtype":  "Power",
        "Description":  "Not needed?",
        "Prerequisite":  "",
        "Cost":  "10",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_frccamo03.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Feat",
        "Subtype":  "Power",
        "Description":  "Not needed?",
        "Prerequisite":  "",
        "Cost":  "15",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_gearhead01.png",
        "Icon":  "",
        "Name":  "Gear Head",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "5",
        "Visible":  "TRUE"
    },
    {
        "File name":  "if_gearhead02.png",
        "Icon":  "",
        "Name":  "Improved Gear Head",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Gear Head",
        "Cost":  "10",
        "Visible":  "TRUE"
    },
    {
        "File name":  "if_gearhead03.png",
        "Icon":  "",
        "Name":  "Master Gear Head",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Improved Gear Head",
        "Cost":  "15",
        "Visible":  "TRUE"
    },
    {
        "File name":  "if_gstance.png",
        "Icon":  "",
        "Name":  "?",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_hidden.png",
        "Icon":  "",
        "Name":  "?",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_ignrpain01.png",
        "Icon":  "",
        "Name":  "Ignore Pain I",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "5",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_ignrpain02.png",
        "Icon":  "",
        "Name":  "Ignore Pain II",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Ignore Pain I",
        "Cost":  "10",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_ignrpain03.png",
        "Icon":  "",
        "Name":  "Ignore Pain III",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Ignore Pain II",
        "Cost":  "15",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_immun01.png",
        "Icon":  "",
        "Name":  "Force Immunity: Fear",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "5",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_immun02.png",
        "Icon":  "",
        "Name":  "Force Immunity: Stun",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Force Immunity: Fear",
        "Cost":  "10",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_immun03.png",
        "Icon":  "",
        "Name":  "Force Immunity: Paralysis",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Force Immunity: Stun",
        "Cost":  "15",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_implant01.png",
        "Icon":  "",
        "Name":  "Implant Class I",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "5",
        "Visible":  "TRUE"
    },
    {
        "File name":  "if_implant02.png",
        "Icon":  "",
        "Name":  "Implant Class II",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Implant Class I",
        "Cost":  "10",
        "Visible":  "TRUE"
    },
    {
        "File name":  "if_implant03.png",
        "Icon":  "",
        "Name":  "Implant Class III",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Implant Class II",
        "Cost":  "15",
        "Visible":  "TRUE"
    },
    {
        "File name":  "if_implswtch.png",
        "Icon":  "",
        "Name":  "Implant Switching",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Implant Class I",
        "Cost":  "5",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_incdmg01.png",
        "Icon":  "",
        "Name":  "Increased Combat Damage I",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "5",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_incdmg02.png",
        "Icon":  "",
        "Name":  "Increased Combat Damage II",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Increased Combat Damage I",
        "Cost":  "10",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_incdmg03.png",
        "Icon":  "",
        "Name":  "Increased Combat Damage III",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Increased Combat Damage II",
        "Cost":  "15",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_incmldmg01.png",
        "Icon":  "",
        "Name":  "Increased Melee Damage I",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "5",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_incmldmg02.png",
        "Icon":  "",
        "Name":  "Increased Melee Damage II",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Increased Melee Damage I",
        "Cost":  "10",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_incmldmg03.png",
        "Icon":  "",
        "Name":  "Increased Melee Damage III",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Increased Melee Damage II",
        "Cost":  "15",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_incstr01.png",
        "Icon":  "",
        "Name":  "Inner Strength I",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "5",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_incstr02.png",
        "Icon":  "",
        "Name":  "Inner Strength II",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Inner Strength I",
        "Cost":  "10",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_incstr03.png",
        "Icon":  "",
        "Name":  "Inner Strength III",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Inner Strength II",
        "Cost":  "15",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_ironwill.png",
        "Icon":  "",
        "Name":  "Iron Will",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_jediac01.png",
        "Icon":  "",
        "Name":  "Jedi Sense",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "5",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_jediac02.png",
        "Icon":  "",
        "Name":  "Prestige Sense",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Jedi Sense",
        "Cost":  "10",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_jediac03.png",
        "Icon":  "",
        "Name":  "Greater Prestige Sense",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Prestige Sense",
        "Cost":  "15",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_jedidef01.png",
        "Icon":  "",
        "Name":  "Jedi Defense",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "5",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_jedidef02.png",
        "Icon":  "",
        "Name":  "Advanced Jedi Defense",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Jedi Defense",
        "Cost":  "10",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_jedidef03.png",
        "Icon":  "",
        "Name":  "Master Jedi Defense",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Advanced Jedi Defense",
        "Cost":  "15",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_jump01.png",
        "Icon":  "",
        "Name":  "Force Jump",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "5",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_jump02.png",
        "Icon":  "",
        "Name":  "Improved Force Jump",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Force Jump",
        "Cost":  "10",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_jump03.png",
        "Icon":  "",
        "Name":  "Master Force Jump",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Improved Force Jump",
        "Cost":  "15",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_kineticcomb.png",
        "Icon":  "",
        "Name":  "?",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_lreflexes.png",
        "Icon":  "",
        "Name":  "?",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_lsenlight.png",
        "Icon":  "",
        "Name":  "Light Side I",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_lsenlight01.png",
        "Icon":  "",
        "Name":  "Light Side II",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Light Side I",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_lsenlight02.png",
        "Icon":  "",
        "Name":  "Light Side III",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Light Side II",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_lsenlight03.png",
        "Icon":  "",
        "Name":  "Light Side IV",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Light Side III",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_mandcourg.png",
        "Icon":  "",
        "Name":  "Mandalorian Courage",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_mcraftar01.png",
        "Icon":  "",
        "Name":  "Armor Crafter I",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "5",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_mcraftar02.png",
        "Icon":  "",
        "Name":  "Armor Crafter II",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Armor Crafter I",
        "Cost":  "10",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_mcraftar03.png",
        "Icon":  "",
        "Name":  "Armor Crafter III",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Armor Crafter II",
        "Cost":  "15",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_mcraftwp01.png",
        "Icon":  "",
        "Name":  "Weapon Crafter I",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "5",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_mcraftwp02.png",
        "Icon":  "",
        "Name":  "Weapon Crafter II",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Weapon Crafter I",
        "Cost":  "10",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_mcraftwp03.png",
        "Icon":  "",
        "Name":  "Weapon Crafter III",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Weapon Crafter II",
        "Cost":  "15",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_mentor.png",
        "Icon":  "",
        "Name":  "Mentor",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_mineimmune.png",
        "Icon":  "",
        "Name":  "?",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_mobility.png",
        "Icon":  "",
        "Name":  "Mobility",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_pattack01.png",
        "Icon":  "",
        "Name":  "Power Attack",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "5",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_pattack02.png",
        "Icon":  "",
        "Name":  "Improved Power Attack",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Power Attack",
        "Cost":  "10",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_pattack03.png",
        "Icon":  "",
        "Name":  "Master Power Attack",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Improved Power Attack",
        "Cost":  "15",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_percept.png",
        "Icon":  "",
        "Name":  "?",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_perscloak.png",
        "Icon":  "",
        "Name":  "Personal Cloak",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_pointguard.png",
        "Icon":  "",
        "Name":  "Point Guard",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_preshot01.png",
        "Icon":  "",
        "Name":  "Precise Shot I",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "5",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_preshot02.png",
        "Icon":  "",
        "Name":  "Precise Shot II",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Precise Shot I",
        "Cost":  "10",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_preshot03.png",
        "Icon":  "",
        "Name":  "Precise Shot III",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Precise Shot II",
        "Cost":  "15",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_preshot04.png",
        "Icon":  "",
        "Name":  "Precise Shot IV",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Precise Shot III",
        "Cost":  "20",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_preshot05.png",
        "Icon":  "",
        "Name":  "Precise Shot V",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Precise Shot IV",
        "Cost":  "25",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_pshot01.png",
        "Icon":  "",
        "Name":  "Power Blast",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "5",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_pshot02.png",
        "Icon":  "",
        "Name":  "Improved Power Blast",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Power Blast",
        "Cost":  "10",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_pshot03.png",
        "Icon":  "",
        "Name":  "Master Power Blast",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Improved Power Blast",
        "Cost":  "15",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_regenfp.png",
        "Icon":  "",
        "Name":  "Regenerate Force Points",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_regenvp.png",
        "Icon":  "",
        "Name":  "Regenerate Vitality Points",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_rshot01.png",
        "Icon":  "",
        "Name":  "Rapid Shot",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "5",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_rshot02.png",
        "Icon":  "",
        "Name":  "Improved Rapid Shot",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Rapid Shot",
        "Cost":  "10",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_rshot03.png",
        "Icon":  "",
        "Name":  "Master Rapid shot",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Improved Rapid Shot",
        "Cost":  "15",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_scdac01.png",
        "Icon":  "",
        "Name":  "Scoundrel\u0027s Luck I",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "5",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_scdac02.png",
        "Icon":  "",
        "Name":  "Scoundrel\u0027s Luck II",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Scoundrel\u0027s Luck I",
        "Cost":  "10",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_scdac03.png",
        "Icon":  "",
        "Name":  "Scoundrel\u0027s Luck III",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Scoundrel\u0027s Luck II",
        "Cost":  "15",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_sfoc2wep01.png",
        "Icon":  "",
        "Name":  "Superior Two-Weapon Fighting I",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "?",
        "Cost":  "5",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_sfoc2wep02.png",
        "Icon":  "",
        "Name":  "Superior Two-Weapon Fighting II",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Superior Two-Weapon Fighting I",
        "Cost":  "10",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_sfoc2wep03.png",
        "Icon":  "",
        "Name":  "Superior Two-Weapon Fighting III",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Superior Two-Weapon Fighting II",
        "Cost":  "15",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_sfoclsab01.png",
        "Icon":  "",
        "Name":  "Superior Weapon Focus Lightsaber I",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "?",
        "Cost":  "5",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_sfoclsab02.png",
        "Icon":  "",
        "Name":  "Superior Weapon Focus Lightsaber II",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Superior Weapon Focus Lightsaber I",
        "Cost":  "10",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_sfoclsab03.png",
        "Icon":  "",
        "Name":  "Superior Weapon Focus Lightsaber III",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Superior Weapon Focus Lightsaber II",
        "Cost":  "15",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_shieldbreak.png",
        "Icon":  "",
        "Name":  "Shield Breaker",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_sneak01.png",
        "Icon":  "",
        "Name":  "Sneak Attack I",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "5",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_sneak02.png",
        "Icon":  "",
        "Name":  "Sneak Attack II",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Sneak Attack I",
        "Cost":  "10",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_sneak03.png",
        "Icon":  "",
        "Name":  "Sneak Attack III",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Sneak Attack II",
        "Cost":  "15",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_sneak04.png",
        "Icon":  "",
        "Name":  "Sneak Attack IV",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Sneak Attack III",
        "Cost":  "20",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_sneak05.png",
        "Icon":  "",
        "Name":  "Sneak Attack V",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Sneak Attack IV",
        "Cost":  "25",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_sneak06.png",
        "Icon":  "",
        "Name":  "Sneak Attack VI",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Sneak Attack V",
        "Cost":  "30",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_sneak07.png",
        "Icon":  "",
        "Name":  "Sneak Attack VII",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Sneak Attack VI",
        "Cost":  "35",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_sneak08.png",
        "Icon":  "",
        "Name":  "Sneak Attack VIII",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Sneak Attack VII",
        "Cost":  "40",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_sneak09.png",
        "Icon":  "",
        "Name":  "Sneak Attack IX",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Sneak Attack VIII",
        "Cost":  "45",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_sneak10.png",
        "Icon":  "",
        "Name":  "Sneak Attack X",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Sneak Attack IX",
        "Cost":  "50",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_spirit.png",
        "Icon":  "",
        "Name":  "Spirit",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "Whether it’s a survival instinct or sheer resolve, you won’t give up.",
        "Prerequisite":  "",
        "Cost":  "5",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_spirit02.png",
        "Icon":  "",
        "Name":  "Fighting Spirit",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Spirit",
        "Cost":  "10",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_spirit03.png",
        "Icon":  "",
        "Name":  "Heroic Resolve",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Fighting Spirit",
        "Cost":  "15",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_sshot01.png",
        "Icon":  "",
        "Name":  "Sniper Shot",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "5",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_sshot02.png",
        "Icon":  "",
        "Name":  "Improved Sniper Shot",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Sniper Shot",
        "Cost":  "10",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_sshot03.png",
        "Icon":  "",
        "Name":  "Master Sniper Shot",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Improved Sniper Shot",
        "Cost":  "15",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_stlhrun.png",
        "Icon":  "",
        "Name":  "Stealth Run",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Stealth Walk",
        "Cost":  "10",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_stlhwlk.png",
        "Icon":  "",
        "Name":  "Stealth Walk",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "5",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_strike01.png",
        "Icon":  "",
        "Name":  "Repulsor Strike",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "Release energy stored in capacitors in your arm.",
        "Prerequisite":  "?",
        "Cost":  "5",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_strike02.png",
        "Icon":  "",
        "Name":  "Electrical Strike",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Repulsor Strike",
        "Cost":  "10",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_strike03.png",
        "Icon":  "",
        "Name":  "Gravitonic Strike",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Electrical Strike",
        "Cost":  "15",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_survival.png",
        "Icon":  "",
        "Name":  "Survival",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "The tougher the situation, the more your survival instinct kicks in.",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_target01.png",
        "Icon":  "",
        "Name":  "Targeting I",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "5",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_target02.png",
        "Icon":  "",
        "Name":  "Targeting II",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "10",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_target03.png",
        "Icon":  "",
        "Name":  "Targeting III",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "15",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_target04.png",
        "Icon":  "",
        "Name":  "Targeting IV",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "20",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_target05.png",
        "Icon":  "",
        "Name":  "Targeting V",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "25",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_target06.png",
        "Icon":  "",
        "Name":  "Targeting VI",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "30",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_target07.png",
        "Icon":  "",
        "Name":  "Targeting VII",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "35",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_target08.png",
        "Icon":  "",
        "Name":  "Targeting VIII",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "40",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_target09.png",
        "Icon":  "",
        "Name":  "Targeting IX",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "45",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_target10.png",
        "Icon":  "",
        "Name":  "Targeting X",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "50",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_toughn01.png",
        "Icon":  "",
        "Name":  "Toughness",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "5",
        "Visible":  "TRUE"
    },
    {
        "File name":  "if_toughn02.png",
        "Icon":  "",
        "Name":  "Improved Toughness",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Toughness",
        "Cost":  "10",
        "Visible":  "TRUE"
    },
    {
        "File name":  "if_toughn03.png",
        "Icon":  "",
        "Name":  "Master Toughness",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Improved Toughness",
        "Cost":  "15",
        "Visible":  "TRUE"
    },
    {
        "File name":  "if_unarmspec01.png",
        "Icon":  "",
        "Name":  "Unarmed Specialist I",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "5",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_unarmspec02.png",
        "Icon":  "",
        "Name":  "Unarmed Specialist II",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Unarmed Specialist I",
        "Cost":  "10",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_unarmspec03.png",
        "Icon":  "",
        "Name":  "Unarmed Specialist III",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Unarmed Specialist II",
        "Cost":  "15",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_unarmspec04.png",
        "Icon":  "",
        "Name":  "Unarmed Specialist IV",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Unarmed Specialist III",
        "Cost":  "20",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_unarmspec05.png",
        "Icon":  "",
        "Name":  "Unarmed Specialist V",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Unarmed Specialist IV",
        "Cost":  "25",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_unarmspec06.png",
        "Icon":  "",
        "Name":  "Unarmed Specialist VI",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Unarmed Specialist V",
        "Cost":  "30",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_unarmspec07.png",
        "Icon":  "",
        "Name":  "Unarmed Specialist VII",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Unarmed Specialist VI",
        "Cost":  "35",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_unarmspec08.png",
        "Icon":  "",
        "Name":  "Unarmed Specialist VIII",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Unarmed Specialist VII",
        "Cost":  "40",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_warvet.png",
        "Icon":  "",
        "Name":  "War Veteran",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "5",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_weapfoc01.png",
        "Icon":  "",
        "Name":  "Weapon Focus Blaster Pistol",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "5",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_weapfoc02.png",
        "Icon":  "",
        "Name":  "Weapon Focus Blaster Rifle",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "5",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_weapfoc03.png",
        "Icon":  "",
        "Name":  "Weapon Focus Grenade",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "5",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_weapfoc04.png",
        "Icon":  "",
        "Name":  "Weapon Focus Heavy Blaster",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "5",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_weapfoc05.png",
        "Icon":  "",
        "Name":  "Weapon Focus Lightsaber",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "5",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_weapfoc06.png",
        "Icon":  "",
        "Name":  "Weapon Focus Melee Weapons",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "5",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_weapfoc07.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "5",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_weapfoc08.png",
        "Icon":  "",
        "Name":  "Weapon Focus Rockets",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "5",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_weapprof01.png",
        "Icon":  "",
        "Name":  "Weapon Proficiency Blaster Pistol",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Weapon Focus Blaster Pistol",
        "Cost":  "10",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_weapprof02.png",
        "Icon":  "",
        "Name":  "Weapon Proficiency Blaster Rifle",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Weapon Focus Blaster Rifle",
        "Cost":  "10",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_weapprof03.png",
        "Icon":  "",
        "Name":  "Weapon Proficiency Grenade",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Weapon Focus Grenade",
        "Cost":  "10",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_weapprof04.png",
        "Icon":  "",
        "Name":  "Weapon Proficiency Heavy Blaster",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Weapon Focus Heavy Blaster",
        "Cost":  "10",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_weapprof05.png",
        "Icon":  "",
        "Name":  "Weapon Proficiency Lightsaber",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Weapon Focus Lightsaber",
        "Cost":  "10",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_weapprof06.png",
        "Icon":  "",
        "Name":  "Weapon Proficiency Melee Weapons",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Weapon Focus Melee Weapons",
        "Cost":  "10",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_weapprof07.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "10",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_weapprof08.png",
        "Icon":  "",
        "Name":  "Weapon Proficiency Rockets",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Weapon Focus Rockets",
        "Cost":  "10",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_weapspec01.png",
        "Icon":  "",
        "Name":  "Weapon Specialization Blaster Pistol",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Weapon Proficiency Blaster Pistol",
        "Cost":  "15",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_weapspec02.png",
        "Icon":  "",
        "Name":  "Weapon Specialization Blaster Rifle",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Weapon Proficiency Blaster Rifle",
        "Cost":  "15",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_weapspec03.png",
        "Icon":  "",
        "Name":  "Weapon Specialization Grenade",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Weapon Proficiency Grenade",
        "Cost":  "15",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_weapspec04.png",
        "Icon":  "",
        "Name":  "Weapon Specialization Heavy Blaster",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Weapon Proficiency Heavy Blaster",
        "Cost":  "15",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_weapspec05.png",
        "Icon":  "",
        "Name":  "Weapon Specialization Lightsaber",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Weapon Proficiency Lightsaber",
        "Cost":  "15",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_weapspec06.png",
        "Icon":  "",
        "Name":  "Weapon Specialization Melee Weapons",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Weapon Proficiency Melee Weapons",
        "Cost":  "15",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_weapspec07.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "15",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_weapspec08.png",
        "Icon":  "",
        "Name":  "Weapon Specialization Rockets",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Weapon Proficiency Rockets",
        "Cost":  "15",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_wookieend.png",
        "Icon":  "",
        "Name":  "Wookie Toughness I",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "5",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_wookieend02.png",
        "Icon":  "",
        "Name":  "Wookie Toughness II",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Wookie Toughness I",
        "Cost":  "10",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_wookieend03.png",
        "Icon":  "",
        "Name":  "Wookie Toughness III",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Wookie Toughness II",
        "Cost":  "15",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_wookrage01.png",
        "Icon":  "",
        "Name":  "Rage",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "5",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_wookrage02.png",
        "Icon":  "",
        "Name":  "Fury",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Rage",
        "Cost":  "10",
        "Visible":  "FALSE"
    },
    {
        "File name":  "if_wookrage03.png",
        "Icon":  "",
        "Name":  "Frenzy",
        "Type":  "Feat",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "Fury",
        "Cost":  "15",
        "Visible":  "FALSE"
    }
];
