window.appData = window.appData || {};
window.appData.upgrades = [
    {
        "File name":  "ii_upgrade_053.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor Upgrade",
        "Subtype":  "Underlay",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ii_upgrade_054.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor Upgrade",
        "Subtype":  "Underlay",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ii_upgrade_055.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor Upgrade",
        "Subtype":  "Underlay",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ii_upgrade_056.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor Upgrade",
        "Subtype":  "Underlay",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ii_upgrade_057.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor Upgrade",
        "Subtype":  "Underlay",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ii_upgrade_058.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor Upgrade",
        "Subtype":  "Underlay",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ii_upgrade_059.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor Upgrade",
        "Subtype":  "Underlay",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ii_upgrade_060.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor Upgrade",
        "Subtype":  "Underlay",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ii_upgrade_061.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor Upgrade",
        "Subtype":  "Underlay",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ii_upgrade_062.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor Upgrade",
        "Subtype":  "Underlay",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ii_upgrade_063.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor Upgrade",
        "Subtype":  "Underlay",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ii_upgrade_064.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor Upgrade",
        "Subtype":  "Underlay",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ii_upgrade_069.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor Upgrade",
        "Subtype":  "Underlay",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ii_upgrade_070.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor Upgrade",
        "Subtype":  "Underlay",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ii_upgrade_205.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor Upgrade",
        "Subtype":  "Overlay",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ii_upgrade_206.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor Upgrade",
        "Subtype":  "Overlay",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ii_upgrade_207.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor Upgrade",
        "Subtype":  "Overlay",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ii_upgrade_208.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor Upgrade",
        "Subtype":  "Overlay",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ii_upgrade_209.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor Upgrade",
        "Subtype":  "Overlay",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ii_upgrade_210.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor Upgrade",
        "Subtype":  "Overlay",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ii_upgrade_211.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor Upgrade",
        "Subtype":  "Overlay",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ii_upgrade_212.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor Upgrade",
        "Subtype":  "Overlay",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ii_upgrade_213.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor Upgrade",
        "Subtype":  "Overlay",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ii_upgrade_214.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor Upgrade",
        "Subtype":  "Overlay",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ii_upgrade_215.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor Upgrade",
        "Subtype":  "Overlay",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ii_upgrade_216.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor Upgrade",
        "Subtype":  "Overlay",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ii_upgrade_217.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor Upgrade",
        "Subtype":  "Overlay",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ii_upgrade_218.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor Upgrade",
        "Subtype":  "Overlay",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ii_upgrade_219.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor Upgrade",
        "Subtype":  "Overlay",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ii_upgrade_220.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor Upgrade",
        "Subtype":  "Overlay",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ii_upgrade_221.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor Upgrade",
        "Subtype":  "Overlay",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ii_upgrade_222.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor Upgrade",
        "Subtype":  "Overlay",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ii_upgrade_223.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor Upgrade",
        "Subtype":  "Overlay",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ii_upgrade_224.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor Upgrade",
        "Subtype":  "Overlay",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ii_upgrade_225.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor Upgrade",
        "Subtype":  "Overlay",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ii_upgrade_226.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor Upgrade",
        "Subtype":  "Overlay",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ii_upgrade_227.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor Upgrade",
        "Subtype":  "Overlay",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ii_upgrade_228.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor Upgrade",
        "Subtype":  "Overlay",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ii_upgrade_229.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor Upgrade",
        "Subtype":  "Overlay",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ii_upgrade_230.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor Upgrade",
        "Subtype":  "Overlay",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ii_upgrade_231.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor Upgrade",
        "Subtype":  "Overlay",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ii_upgrade_232.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor Upgrade",
        "Subtype":  "Overlay",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ii_upgrade_233.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor Upgrade",
        "Subtype":  "Overlay",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ii_upgrade_234.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor Upgrade",
        "Subtype":  "Overlay",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ii_upgrade_235.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor Upgrade",
        "Subtype":  "Overlay",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ii_upgrade_236.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor Upgrade",
        "Subtype":  "Underlay",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ii_upgrade_237.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor Upgrade",
        "Subtype":  "Underlay",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ii_upgrade_238.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor Upgrade",
        "Subtype":  "Underlay",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ii_upgrade_239.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor Upgrade",
        "Subtype":  "Underlay",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ii_upgrade_240.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor Upgrade",
        "Subtype":  "Underlay",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ii_upgrade_241.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor Upgrade",
        "Subtype":  "Underlay",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ii_upgrade_242.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor Upgrade",
        "Subtype":  "Underlay",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ii_upgrade_243.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor Upgrade",
        "Subtype":  "Underlay",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ii_upgrade_244.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor Upgrade",
        "Subtype":  "Underlay",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ii_upgrade_245.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor Upgrade",
        "Subtype":  "Underlay",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ii_upgrade_246.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor Upgrade",
        "Subtype":  "Underlay",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ii_upgrade_247.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor Upgrade",
        "Subtype":  "Underlay",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ii_upgrade_248.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor Upgrade",
        "Subtype":  "Underlay",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ii_upgrade_249.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor Upgrade",
        "Subtype":  "Underlay",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ii_upgrade_250.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor Upgrade",
        "Subtype":  "Underlay",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ii_upgrade_251.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor Upgrade",
        "Subtype":  "Underlay",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ii_upgrade_252.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Armor Upgrade",
        "Subtype":  "Underlay",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_064.png",
        "Icon":  "",
        "Name":  "Firing Chamber",
        "Type":  "Blaster Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_065.png",
        "Icon":  "",
        "Name":  "Scope",
        "Type":  "Blaster Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_066.png",
        "Icon":  "",
        "Name":  "Power Cell",
        "Type":  "Blaster Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_067.png",
        "Icon":  "",
        "Name":  "Beam Splitter?",
        "Type":  "Blaster Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_068.png",
        "Icon":  "",
        "Name":  "Trigger",
        "Type":  "Blaster Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_122.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Blaster Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_123.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Blaster Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_124.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Blaster Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_125.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Blaster Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_126.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Blaster Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_127.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Blaster Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_128.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Blaster Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_129.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Blaster Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_130.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Blaster Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_131.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Blaster Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_132.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Blaster Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_133.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Blaster Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_134.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Blaster Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_135.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Blaster Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_136.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Blaster Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_137.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Blaster Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_138.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Blaster Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_139.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Blaster Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_140.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Blaster Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_141.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Blaster Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_142.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Blaster Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_143.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Blaster Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_144.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Blaster Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_145.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Blaster Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_146.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Blaster Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_147.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Blaster Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_148.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Blaster Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_149.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Blaster Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_150.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Blaster Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_151.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Blaster Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_152.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Blaster Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_153.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Blaster Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_154.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Blaster Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_155.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Blaster Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_156.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Blaster Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_157.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Blaster Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_158.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Blaster Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_159.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Blaster Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_160.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Blaster Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_161.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Blaster Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_162.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Blaster Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_163.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Blaster Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_164.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Melee Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_165.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Melee Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_166.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Melee Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_167.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Melee Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_168.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Melee Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_169.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Melee Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_170.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Melee Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_171.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Melee Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_172.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Melee Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_173.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Melee Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_174.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Melee Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_175.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Melee Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_176.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Melee Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_177.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Melee Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_178.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Melee Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_179.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Melee Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_180.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Melee Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_181.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Melee Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_182.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Melee Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_183.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Melee Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_184.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Melee Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_185.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Melee Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_186.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Melee Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_187.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Melee Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_188.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Melee Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_189.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Melee Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_190.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Melee Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_191.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Melee Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_192.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Melee Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_193.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Melee Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_194.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Melee Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_195.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Melee Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_196.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Melee Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_197.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Melee Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_198.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Melee Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_199.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Melee Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_200.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Melee Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_201.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Melee Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_202.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Melee Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_203.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Melee Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_204.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Melee Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_205.png",
        "Icon":  "",
        "Name":  "Cell",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Cell",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_206.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Cell",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_207.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Cell",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_208.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Cell",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_209.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Cell",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_210.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Cell",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_211.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Cell",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_212.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Cell",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_213.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Cell",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_214.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Cell",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_215.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Cell",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_216.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Cell",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_217.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Cell",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_218.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Emitter",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_219.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Emitter",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_220.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Emitter",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_221.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Emitter",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_222.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Emitter",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_223.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Emitter",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_224.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Emitter",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_225.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Emitter",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_226.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Emitter",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_227.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Emitter",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_228.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Emitter",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_229.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Emitter",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_230.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Emitter",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_231.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Emitter",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_232.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Lens",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_233.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Lens",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_234.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Lens",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_235.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Lens",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_236.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Lens",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_237.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Lens",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_238.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Lens",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_239.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Lens",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_240.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Lens",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_241.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Lens",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_242.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Lens",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_243.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Lens",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_244.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Lens",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_245.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Lens",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_246.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Melee Upgrade",
        "Subtype":  "Hilt",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_247.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Melee Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_248.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_249.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_250.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Cell",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "iw_SbrCrstl_001.png",
        "Icon":  "",
        "Name":  "Crystal, Opila",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Power Crystal",
        "Description":  "Found in the asteroid fields of the Fyrth system, this crystal can be used in lightsaber construction to produce an intense beam that seems extraordinarily quick to the cut.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "TRUE"
    },
    {
        "File name":  "iw_sbrcrstl_002.png",
        "Icon":  "",
        "Name":  "Crystal, Bondar",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Power Crystal",
        "Description":  "This crystal was mined on a far-orbit asteroid circling the Alderaan system. It produces a volatile lightsaber beam that pulses on impact, potentially stunning an opponent.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "TRUE"
    },
    {
        "File name":  "iw_sbrcrstl_002.png",
        "Icon":  "",
        "Name":  "Crystal, Phond",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Power Crystal",
        "Description":  "The strange byproduct of rare impurities bonding during the making of certain alloys and some random external condition, this crystal produces a fiercely burning lightsaber beam.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "TRUE"
    },
    {
        "File name":  "iw_sbrcrstl_003.png",
        "Icon":  "",
        "Name":  "Crystal, Damind",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Power Crystal",
        "Description":  "Found on the desert world of Daminia, this crystal can be used in lightsaber construction to produce a clearly defined beam of subtly wider width and length.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "TRUE"
    },
    {
        "File name":  "iw_sbrcrstl_004.png",
        "Icon":  "",
        "Name":  "Crystal, Rubat",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Power Crystal",
        "Description":  "Used in lightsaber construction, rubat crystal is mined on Phemis. It produces a clearly defined blade that a Jedi can easily track, making it easier to hit opponents.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "TRUE"
    },
    {
        "File name":  "iw_sbrcrstl_004.png",
        "Icon":  "",
        "Name":  "Crystal, Eralam",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Power Crystal",
        "Description":  "Once mined on the third moon of Erai, ancient Sith bombardment shattered much that remained. If they can be found, these crystals produce a clear, superior lightsaber beam.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "TRUE"
    },
    {
        "File name":  "iw_sbrcrstl_005.png",
        "Icon":  "",
        "Name":  "Crystal, Firkrann",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Power Crystal",
        "Description":  "This heavy crystal is collected by the natives of Rafa V. If used in lightsaber construction it produces an electrically charged beam that is devastating to droids.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "TRUE"
    },
    {
        "File name":  "iw_sbrcrstl_013.png",
        "Icon":  "",
        "Name":  "Crystal, Sapith",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Power Crystal",
        "Description":  "This crystallized material was excreted once every 11 years by the ancient Volice worm of Lwhekk, now extinct. It produces a more intense lightsaber beam, granting better control.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "TRUE"
    },
    {
        "File name":  "iw_sbrcrstl_031a.png",
        "Icon":  "",
        "Name":  "Crystal, Solari",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Power Crystal",
        "Description":  "There are many famous lightsaber crystals spoken of in the history of the Jedi Order. An artifact of true light side power, only those Jedi who are pure in spirit can wield a lightsaber equipped with this gleaming white gem.\r\n \r\nWhen the great Jedi Master Ood Bnar initiated his life-cycle change after a thousand years of serving the Order, he bequeathed the Solari crystal to his most promising student, a young female Jedi named Shaela Nuur. When Shaela disappeared shortly after the time of the Great Hunt, the Solari crystal vanished with her.",
        "Prerequisite":  "Light Side",
        "Cost":  "1",
        "Visible":  "TRUE"
    },
    {
        "File name":  "iw_sbrcrstl_006.png",
        "Icon":  "",
        "Name":  "Crystal, Sigil",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Power Crystal",
        "Description":  "Mined in the Sigil System, this crystal is a costly but valued addition to a lightsaber. It produces a fiercely bright beam that sears on contact, inflicting great damage.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "TRUE"
    },
    {
        "File name":  "iw_sbrcrstl_007.png",
        "Icon":  "",
        "Name":  "Crystal, Upari",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Power Crystal",
        "Description":  "Strangely, this crystal is usually encountered scattered in the orbit of primarily forest worlds. It is brittle but versatile, and a Master Jedi can get it to produce many effects.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "TRUE"
    },
    {
        "File name":  "iw_sbrcrstl_008.png",
        "Icon":  "",
        "Name":  "Crystal, Jenruax",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Power Crystal",
        "Description":  "The refined form of Opila, this crystal has been cleansed of all impurities. When used in lightsaber construction it produces a blade of unerring quickness.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "TRUE"
    },
    {
        "File name":  "iw_sbrcrstl_009.png",
        "Icon":  "",
        "Name":  "Crystal, Dragite",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Power Crystal",
        "Description":  "Dragite crystals are found on M\u0027haeli, in the D\u0027olop mountain range. The beam they create resonates loudly when it strikes, inflicting a minor amount of sonic damage.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "TRUE"
    },
    {
        "File name":  "iw_sbrcrstl_010.png",
        "Icon":  "",
        "Name":  "Crystal, Silver",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Color Crystal",
        "Description":  "A faceted crystal used in the constructing of a lightsaber. It glows faintly with a silvery light.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "TRUE"
    },
    {
        "File name":  "iw_sbrcrstl_012.png",
        "Icon":  "",
        "Name":  "Crystal, Nextor",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Power Crystal",
        "Description":  "This crystal is mined in the mountains of planet M\u0027haeli, and when used in lightsaber construction it produces a volatile blade that can cause surprising amounts of damage.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "TRUE"
    },
    {
        "File name":  "iw_sbrcrstl_011.png",
        "Icon":  "",
        "Name":  "Crystal, Ruusan",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Power Crystal",
        "Description":  "Ruusan crystals come from the Mid Rim planet of the same name. While not directly affecting a lightsaber\u0027s effectiveness, they aid a Jedi in focusing the Force.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "TRUE"
    },
    {
        "File name":  "iw_sbrcrstl_014.png",
        "Icon":  "",
        "Name":  "Crystal, Blue",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Color Crystal",
        "Description":  "A facetted crystal used in the constructing of a lightsaber. It glows faintly with an inner blue light.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "TRUE"
    },
    {
        "File name":  "iw_sbrcrstl_015.png",
        "Icon":  "",
        "Name":  "Crystal, Yellow",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Color Crystal",
        "Description":  "A facetted crystal used in the constructing of a lightsaber. It glows faintly with an inner yellow light.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "TRUE"
    },
    {
        "File name":  "iw_sbrcrstl_016.png",
        "Icon":  "",
        "Name":  "Crystal, Green",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Color Crystal",
        "Description":  "A facetted crystal used in the constructing of a lightsaber. It glows faintly with an inner green light.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "TRUE"
    },
    {
        "File name":  "iw_sbrcrstl_017.png",
        "Icon":  "",
        "Name":  "Crystal, Pontite",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Power Crystal",
        "Description":  "Pontite is one of the rarest forms of Adegan crystal. It radiates a powerful aura that cools both skin and tempers.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "TRUE"
    },
    {
        "File name":  "iw_sbrcrstl_017.png",
        "Icon":  "",
        "Name":  "Crystal, Violet",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Color Crystal",
        "Description":  "A facetted crystal used in the constructing of a lightsaber. It glows faintly with an inner violet light.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "TRUE"
    },
    {
        "File name":  "iw_sbrcrstl_018.png",
        "Icon":  "",
        "Name":  "Crystal, Red",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Color Crystal",
        "Description":  "A facetted crystal used in the constructing of a lightsaber. It glows faintly with an inner red light.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "TRUE"
    },
    {
        "File name":  "iw_sbrcrstl_020.png",
        "Icon":  "",
        "Name":  "Crystal, Bronze",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Color Crystal",
        "Description":  "A facetted crystal used in the constructing of a lightsaber. Yellowish-brown in color, the same sort of crystal is sometimes used in high resolution displays.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "TRUE"
    },
    {
        "File name":  "iw_sbrcrstl_021.png",
        "Icon":  "",
        "Name":  "Crystal, Cyan",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Color Crystal",
        "Description":  "A faceted crystal used in the constructing of a lightsaber. It glows faintly with an inner cyan light.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "TRUE"
    },
    {
        "File name":  "iw_sbrcrstl_022.png",
        "Icon":  "",
        "Name":  "Crystal, Adegan",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Power Crystal",
        "Description":  "Adegan crystals, also called Ilum crystals, are one of the most common lightsaber focusing crystals.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "TRUE"
    },
    {
        "File name":  "iw_sbrcrstl_023.png",
        "Icon":  "",
        "Name":  "Crystal, Orange",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Color Crystal",
        "Description":  "A facetted crystal used in the constructing of a lightsaber. It glows faintly with an inner orange light.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "TRUE"
    },
    {
        "File name":  "iw_sbrcrstl_024.png",
        "Icon":  "",
        "Name":  "Crystal, Viridian",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Color Crystal",
        "Description":  "A faceted crystal used in the constructing of a lightsaber. It glows faintly with a silvery green light.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "TRUE"
    },
    {
        "File name":  "iw_sbrcrstl_025.png",
        "Icon":  "",
        "Name":  "Crystal, Velmorite",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Power Crystal",
        "Description":  "Found only on the planet Velmor, these crystals produce a very fine beam that is easy to wield skillfully.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "TRUE"
    },
    {
        "File name":  "iw_sbrcrstl_026.png",
        "Icon":  "",
        "Name":  "Crystal, Kasha",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Power Crystal",
        "Description":  "This crystal is traditionally used by the Cereans as a meditation tool. When used as a lightsaber crystal, it helps clear the wielder\u0027s mind of distractions, even during tense combat.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "TRUE"
    },
    {
        "File name":  "iw_sbrcrstl_027.png",
        "Icon":  "",
        "Name":  "Crystal, Stygium",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Power Crystal",
        "Description":  "The stygium mineral can be used to create cloaking effects that foil enemy sensors. In its pure crystal form, it is suitable for a lightsaber.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "TRUE"
    },
    {
        "File name":  "iw_sbrcrstl_028.png",
        "Icon":  "",
        "Name":  "Crystal, Hurrikaine",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Power Crystal",
        "Description":  "The very rare Hurrikaine crystal is best known for its unparalleled beauty. When used in a lightsaber, the dark gemstone creates a devastating beam that can partially penetrate any defenses.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "TRUE"
    },
    {
        "File name":  "iw_sbrcrstl_029.png",
        "Icon":  "",
        "Name":  "Ultima-Pearl",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Power Crystal",
        "Description":  "An unusual choice for a lightsaber focusing crystal, this rare stone can be found on Calamari. Difficult to properly install in a lightsaber, this valuable stone has powerful effects.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "TRUE"
    },
    {
        "File name":  "iw_sbrcrstl_030.png",
        "Icon":  "",
        "Name":  "Lorrdian Gemstone",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Power Crystal",
        "Description":  "During their subjugation, the Lorrdians were banned from speaking to each other and thus learned to use subtle gestures and ticks to communicate. The few Force-Adepts found after the Jedi freed the population of slaves has imprinted these gemstones with the Force to enhance the ability to read an opponent.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "TRUE"
    },
    {
        "File name":  "iw_sbrcrstl_031.png",
        "Icon":  "",
        "Name":  "Barab Ore Ingot",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Power Crystal",
        "Description":  "The ore from Barab I actually lies on the planets surface, meaning it is exposed to high doses of radiation and torrential downpours daily. This ore can be found in concentrated ingots that actual store and magnify the radiation.\r\n \r\nWhen placed in a lightsaber, the ingots produce a blade that burns almost to the point of losing its cohesion.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "TRUE"
    },
    {
        "File name":  "iw_sbrcrstl_032.png",
        "Icon":  "",
        "Name":  "Crystal, Kaiburr",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Power Crystal",
        "Description":  "Perhaps the most powerful crystal that can be used in a lightsaber, the Kaiburr gem bestows insight and fortitute upon its owner.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "TRUE"
    },
    {
        "File name":  "iw_sbrcrstl_033.png",
        "Icon":  "",
        "Name":  "Ankarres Sapphire",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Power Crystal",
        "Description":  "This crystal possesses legendary healing powers and numerous other effects. It is one of the most potent crystals that can be used in lightsaber creation.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "TRUE"
    },
    {
        "File name":  "iw_sbrcrstl_034.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Power Crystal",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "iw_sbrcrstl_035.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Power Crystal",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "iw_sbrcrstl_036.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Power Crystal",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "iw_sbrcrstl_037.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Power Crystal",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "iw_sbrcrstl_038.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Power Crystal",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "iw_sbrcrstl_039.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Power Crystal",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "iw_sbrcrstl_040.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Power Crystal",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "iw_sbrcrstl_041.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Power Crystal",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "iw_sbrcrstl_042.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Power Crystal",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "iw_sbrcrstl_043.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Power Crystal",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "iw_sbrcrstl_044.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Power Crystal",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "iw_sbrcrstl_045.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Power Crystal",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "iw_sbrcrstl_046.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Power Crystal",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "iw_sbrcrstl_047.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Power Crystal",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "iw_sbrcrstl_048.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Power Crystal",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "iw_sbrcrstl_049.png",
        "Icon":  "",
        "Name":  "Crystal, Qixoni",
        "Type":  "Lightsaber Upgrade",
        "Subtype":  "Power Crystal",
        "Description":  "Qixoni crystals were formed on a planet that was destroyed millenia ago when its star went supernova. They are exceedingly rare and also quite powerful.",
        "Prerequisite":  "",
        "Cost":  "1",
        "Visible":  "TRUE"
    },
    {
        "File name":  "ip_pltuseitm_003.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Melee Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    },
    {
        "File name":  "ip_pltuseitm_004.png",
        "Icon":  "",
        "Name":  "",
        "Type":  "Melee Upgrade",
        "Subtype":  "",
        "Description":  "",
        "Prerequisite":  "",
        "Cost":  "",
        "Visible":  "FALSE"
    }
];
